[general]
background
horizontal_rule
unread_indicator
border

[text]
primary
secondary
tertiary
success
error

[buffer]
background
background_text_input
background_title_bar
timestamp
action
highlight
selection
border_selected

[buttons.primary]
background
background_hover
background_selected
background_selected_hover

[buttons.secondary]
background
background_hover
background_selected
background_selected_hover
