[general]
background
horizontal_rule
unread_indicator
border

[text]
primary
secondary
tertiary
success
error

[buttons.primary]
background
background_hover
background_selected
background_selected_hover

[buttons.secondary]
background
background_hover
background_selected
background_selected_hover
